export const AVERAGE_HUMBLE_FUD_BASE_ALCHEMICA: number = 7077;
export const AVERAGE_HUMBLE_FOMO_BASE_ALCHEMICA: number = 3539;
export const AVERAGE_HUMBLE_ALPHA_BASE_ALCHEMICA: number = 1769;
export const AVERAGE_HUMBLE_KEK_BASE_ALCHEMICA: number = 708;

export const MIN_HUMBLE_FUD_BASE_ALCHEMICA: number = 1415;
export const MIN_HUMBLE_FOMO_BASE_ALCHEMICA: number = 707;
export const MIN_HUMBLE_ALPHA_BASE_ALCHEMICA: number = 353;
export const MIN_HUMBLE_KEK_BASE_ALCHEMICA: number = 141;

export const MAX_HUMBLE_FUD_BASE_ALCHEMICA: number = 12738;
export const MAX_HUMBLE_FOMO_BASE_ALCHEMICA: number = 6370;
export const MAX_HUMBLE_ALPHA_BASE_ALCHEMICA: number = 3184;
export const MAX_HUMBLE_KEK_BASE_ALCHEMICA: number = 1274;

export const AVERAGE_REASONABLE_FUD_BASE_ALCHEMICA: number = 28308;
export const AVERAGE_REASONABLE_FOMO_BASE_ALCHEMICA: number = 14154;
export const AVERAGE_REASONABLE_ALPHA_BASE_ALCHEMICA: number = 7077;
export const AVERAGE_REASONABLE_KEK_BASE_ALCHEMICA: number = 2831;

export const MIN_REASONABLE_FUD_BASE_ALCHEMICA: number = 5661;
export const MIN_REASONABLE_FOMO_BASE_ALCHEMICA: number = 2830;
export const MIN_REASONABLE_ALPHA_BASE_ALCHEMICA: number = 1215;
export const MIN_REASONABLE_KEK_BASE_ALCHEMICA: number = 566;

export const MAX_REASONABLE_FUD_BASE_ALCHEMICA: number = 50954;
export const MAX_REASONABLE_FOMO_BASE_ALCHEMICA: number = 25477;
export const MAX_REASONABLE_ALPHA_BASE_ALCHEMICA: number = 12738;
export const MAX_REASONABLE_KEK_BASE_ALCHEMICA: number = 5095;

export const AVERAGE_SPACIOUS_FUD_BASE_ALCHEMICA: number = 226465;
export const AVERAGE_SPACIOUS_FOMO_BASE_ALCHEMICA: number = 113233;
export const AVERAGE_SPACIOUS_ALPHA_BASE_ALCHEMICA: number = 56616;
export const AVERAGE_SPACIOUS_KEK_BASE_ALCHEMICA: number = 22647;

export const MIN_SPACIOUS_FUD_BASE_ALCHEMICA: number = 45293;
export const MIN_SPACIOUS_FOMO_BASE_ALCHEMICA: number = 22646;
export const MIN_SPACIOUS_ALPHA_BASE_ALCHEMICA: number = 11323;
export const MIN_SPACIOUS_KEK_BASE_ALCHEMICA: number = 4529;

export const MAX_SPACIOUS_FUD_BASE_ALCHEMICA: number = 407637;
export const MAX_SPACIOUS_FOMO_BASE_ALCHEMICA: number = 203819;
export const MAX_SPACIOUS_ALPHA_BASE_ALCHEMICA: number = 101908;
export const MAX_SPACIOUS_KEK_BASE_ALCHEMICA: number = 40764;
