export enum WearableItemTypes {
    Accessory = 'Accessory',
    AlcoholicBeverage = 'Alcoholic Beverage',
    Animal = 'Animal',
    Artifact = 'Artifact',
    Bag = 'Bag',
    BigHat = 'Big Hat',
    BodyPart = 'Body Part',
    Cap = 'Cap',
    Comfywear = 'Comfywear',
    Dress = 'Dress',
    DressShirt = 'Dress Shirt',
    DressSuit = 'Dress Suit',
    Electronics = 'Electronics',
    Eye = 'Eye',
    FacialHair = 'Facial Hair',
    Glasses = 'Glasses',
    Hair = 'Hair',
    Hat = 'Hat',
    HealthyBeverage = 'Healthy Beverage',
    HealthyEdible = 'Healthy Edible',
    HeavyArmor = 'Heavy Armor',
    Helmet = 'Helmet',
    Jacket = 'Jacket',
    Jewelry = 'Jewelry',
    KnitHat = 'Knit Hat',
    LightArmor = 'Light Armor',
    LongHair = 'Long Hair',
    Mask = 'Mask',
    Pants = 'Pants',
    Pillow = 'Pillow',
    Plant = 'Plant',
    ProtectiveSuit = 'Protective Suit',
    Robe = 'Robe',
    Shades = 'Shades',
    Shield = 'Shield',
    Sign = 'Sign',
    Sportswear = 'Sportswear',
    TShirt = 'T-Shirt',
    Token = 'Token',
    UnhealthyEdible = 'Unhealthy Edible',
    Vehicle = 'Vehicle',
    Wings = 'Wings',
    // weapons
    MeleeWeapon = 'Melee Weapon',
    RangedWeapon = 'Ranged Weapon',
}

export enum WerableBenefitTypes {
    AlchemicaSpeed = 'Alchemica Speed',
    APCapacity = 'AP Capacity',
    APRegen = 'AP Regen',
    ArmorPower = 'Armor Power',
    CarryingCapacity = 'Carrying Capacity',
    Evasion = 'Evasion',
    HPCapacity = 'HP Capacity',
    HPRegen = 'HP Regen',
    Luck = 'Luck',
    MovementSpeed = 'Movement Speed',
    RoadSpeed = 'Road Speed',
    VisionRange = 'Vision Range',
    // weapons
    Unknown = 'Unknown'
}
